# About Dataset

Dataset Air Quality Data in India yang tersedia di Kaggle berisi informasi mengenai kondisi kualitas udara di berbagai kota di India dalam rentang waktu sekitar tahun 2015 hingga 2020. Data ini dikumpulkan oleh Central Pollution Control Board sebagai lembaga resmi pemerintah yang bertugas memantau dan mengendalikan tingkat pencemaran udara. Secara umum, dataset ini merepresentasikan bagaimana kualitas udara berubah dari waktu ke waktu akibat aktivitas manusia seperti transportasi, industri, dan faktor lingkungan lainnya, sehingga sangat relevan untuk analisis lingkungan maupun kesehatan masyarakat.

Data disajikan dalam bentuk harian untuk setiap kota, yang mencakup informasi tanggal dan lokasi serta berbagai parameter polutan udara. Variabel-variabel tersebut meliputi konsentrasi partikel seperti PM2.5 dan PM10, serta gas berbahaya seperti karbon monoksida (CO), nitrogen dioksida (NO2), sulfur dioksida (SO2), ozon (O3), dan beberapa senyawa organik volatil seperti benzena dan toluena. Seluruh parameter ini biasanya diukur dalam satuan mikrogram per meter kubik (µg/m³) dan digunakan untuk menggambarkan tingkat pencemaran udara pada hari tertentu di suatu kota.

Selain itu, dataset ini juga menyediakan nilai Air Quality Index (AQI) yang merupakan indikator utama untuk menilai kualitas udara secara keseluruhan. AQI dihitung berdasarkan beberapa polutan utama, di mana nilai tertinggi dari sub-indeks polutan digunakan sebagai representasi kondisi udara. Dataset juga menyertakan kategori kualitas udara dalam bentuk AQI_Bucket, seperti Good, Moderate, Poor, hingga Severe.

# Library

In [111]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

# Load Data

In [112]:
df = pd.read_excel("/content/Data_Preprocessing2.xlsx")

df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

# EDA (Exploratory Data Analysis)

In [113]:
print("Shape data:", df.shape)

Shape data: (29531, 16)

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB

In [115]:
df.describe()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
count,24933.000000,18391.000000,25949.000000,25946.000000,25346.000000,19203.000000,27472.000000,25677.000000,25509.000000,23908.000000,21490.000000,11422.000000,24850.000000
mean,67.450578,118.127103,17.574730,28.560659,32.309123,23.483476,2.248598,14.531977,34.491430,3.280840,8.700972,3.070128,166.463581
std,64.661449,90.605110,22.785846,24.474746,31.646011,25.684275,6.962884,18.133775,21.694928,15.811136,19.969164,6.323247,140.696585
min,0.040000,0.010000,0.020000,0.010000,0.000000,0.010000,0.000000,0.010000,0.010000,0.000000,0.000000,0.000000,13.000000
25%,28.820000,56.255000,5.630000,11.750000,12.820000,8.580000,0.510000,5.670000,18.860000,0.120000,0.600000,0.140000,81.000000
50%,48.570000,95.680000,9.890000,21.690000,23.520000,15.850000,0.890000,9.160000,30.840000,1.070000,2.970000,0.980000,118.000000
75%,80.590000,149.745000,19.950000,37.620000,40.127500,30.020000,1.450000,15.220000,45.570000,3.080000,9.150000,3.350000,208.000000
max,949.990000,1000.000000,390.680000,362.210000,467.630000,352.890000,175.810000,193.860000,257.730000,455.030000,454.850000,170.370000,2049.000000

In [116]:
df.isnull().sum().sort_values(ascending=False)

Xylene        18109
PM10          11140
NH3           10328
Toluene        8041
Benzene        5623
AQI            4681
AQI_Bucket     4681
PM2.5          4598
NOx            4185
O3             4022
SO2            3854
NO2            3585
NO             3582
CO             2059
Date              0
City              0
dtype: int64

In [117]:
(df == 0).sum().sort_values(ascending=False)

Benzene       3802
Toluene       2861
CO            2328
Xylene        1747
NOx            740
City             0
PM2.5            0
Date             0
NH3              0
NO2              0
NO               0
PM10             0
O3               0
SO2              0
AQI              0
AQI_Bucket       0
dtype: int64

# Cleaning Data

In [118]:
df['Date'] = pd.to_datetime(df['Date'])

df = df.sort_values('Date')
df = df.set_index('Date')

In [119]:
df = df.drop_duplicates()

Baris yang tidak memiliki informasi signifikan (seluruh kolom numerik kosong) dihapus untuk menjaga kualitas data yang digunakan.

In [120]:
cols_to_check = df.columns.difference(['City'])
df = df.dropna(subset=cols_to_check, how='all')

# Handling Nilai 0

Pada beberapa variabel tertentu, nilai nol dianggap tidak valid sehingga dikonversi menjadi missing value (NaN) agar dapat ditangani dengan metode imputasi yang sesuai

In [121]:
cols_invalid_zero = ['Benzene', 'Toluene', 'CO', 'Xylene', 'NOx']
df[cols_invalid_zero] = df[cols_invalid_zero].replace(0, np.nan)

# Handling Missing Value

Kolom dalam dataset dipisahkan menjadi dua kategori, yaitu kolom numerik dan kolom kategorikal, untuk mempermudah proses preprocessing yang sesuai dengan karakteristik masing-masing data.

In [122]:
num_cols = df.select_dtypes(include=['float64','int64']).columns
cat_cols = df.select_dtypes(include=['object']).columns

Nilai yang hilang pada kolom numerik diisi menggunakan metode interpolasi linear dan median, sedangkan pada kolom kategorikal diisi menggunakan nilai modus. Pendekatan ini bertujuan untuk mempertahankan distribusi data.

In [123]:
df[num_cols] = df[num_cols].interpolate(method='linear')
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

for col in cat_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

# Handling Outliers (IQR)

Outlier ditangani menggunakan metode Interquartile Range (IQR) dengan teknik capping, yaitu membatasi nilai ekstrem agar berada dalam rentang yang wajar tanpa menghapus data.

In [124]:
def handle_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df[column] = df[column].clip(lower, upper)
    return df

for col in num_cols:
    df = handle_outliers_iqr(df, col)

# Feature Engineering

Dilakukan ekstraksi fitur baru dari data tanggal, yaitu tahun dan bulan untuk menambah informasi yang dapat digunakan dalam analisis atau pemodelan.

In [125]:
df['year'] = df.index.year
df['month'] = df.index.month

# Split Data

In [131]:
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df, test_size=0.2, random_state=42)

print(f"Shape of training data: {df_train.shape}")
print(f"Shape of testing data: {df_test.shape}")

Shape of training data: (21771, 17)
Shape of testing data: (5443, 17)

In [132]:
output_file = 'train_test_data.xlsx'
with pd.ExcelWriter(output_file) as writer:
    df_train.to_excel(writer, sheet_name='Train_Data', index=True)
    df_test.to_excel(writer, sheet_name='Test_Data', index=True)
print(f"Data train dan test telah disimpan ke '{output_file}' dengan sheet terpisah.")

Data train dan test telah disimpan ke 'train_test_data.xlsx' dengan sheet terpisah.